### ISSUE TITLE
change stelligent-nu repo to a template

### ISSUE THREAD

**Issue by oshaughnessy** [stelligent/stelligent-u#2]
See https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template:

> Creating a repository from a template is similar to forking a repository, but there are important differences:
> 
> * A new fork includes the entire commit history of the parent repository, while a repository created from a template starts with a single commit.
> * Commits to a fork don't appear in your contributions graph, while commits to a repository created from a template do appear in your contribution graph.
> * A fork can be a temporary way to contribute code to an existing project, while creating a repository from a template starts a new project quickly.

stelligent-nu was marked as a template. It encourages the behavior we want for people going through the program and steers them away from the actions a repo contributor would take to copy the repo.

**Comment by jtulick** [comment]
Agreed and done.
